<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api } from '@/services/api'
import AdminPageHeader from '@/components/common/AdminPageHeader.vue'
import UiIcon from '@/components/common/UiIcon.vue'
import type { PageResponse, PostSummary } from '@/types'

type Tab='general'|'branding'|'reading'|'seo'|'contact'|'performance'
const tab=ref<Tab>('general');const pages=ref<PostSummary[]>([]);const saved=ref(false);const error=ref('');const loading=ref(true);const saving=ref(false)
const values=reactive<Record<string,string>>({
'site.name':'','site.tagline':'','site.description':'','site.locale':'es-HN','site.timezone':'America/Tegucigalpa',
'branding.logoUrl':'','branding.faviconUrl':'','branding.accentColor':'#6d4aff',
'reading.homePageSlug':'inicio','reading.postsPerPage':'12','reading.showAdminBar':'true','reading.dateFormat':'dd/MM/yyyy',
'seo.titleTemplate':'%s · TrastCMS','seo.defaultDescription':'','seo.robotsIndex':'true',
'contact.email':'','contact.phone':'','contact.address':'','contact.city':'','contact.country':'Honduras','contact.schedule':'','contact.facebook':'','contact.instagram':'','contact.linkedin':'','contact.youtube':'',
'performance.publicCacheSeconds':'300','media.maxUploadMb':'100','comments.enabled':'false','maintenance.enabled':'false'})
const tabs:Array<{id:Tab;label:string;icon:string}>=[{id:'general',label:'General',icon:'settings'},{id:'branding',label:'Identidad',icon:'theme'},{id:'reading',label:'Lectura',icon:'page'},{id:'seo',label:'SEO',icon:'search'},{id:'contact',label:'Contacto',icon:'users'},{id:'performance',label:'Rendimiento',icon:'dashboard'}]
onMounted(async()=>{try{const [result,pageResult]=await Promise.all([api<{values:Record<string,string>}>('/api/admin/settings'),api<PageResponse<PostSummary>>('/api/admin/posts?type=PAGE&size=100')]);Object.assign(values,result.values);pages.value=pageResult.content}catch(e){error.value=e instanceof Error?e.message:'No se pudo cargar'}finally{loading.value=false}})
async function save(){saving.value=true;saved.value=false;error.value='';try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({values:{...values}})});saved.value=true}catch(e){error.value=e instanceof Error?e.message:'No se pudo guardar'}finally{saving.value=false}}
</script>
<template>
 <AdminPageHeader eyebrow="Sistema" title="Configuración del sitio" description="Controle identidad, portada, SEO, contacto y comportamiento general de TrastCMS."><template #actions><button class="button" :disabled="saving||loading" @click="save"><UiIcon name="save" :size="17"/>{{saving?'Guardando…':'Guardar cambios'}}</button></template></AdminPageHeader>
 <div class="grid gap-5 xl:grid-cols-[250px_minmax(0,1fr)]">
  <aside class="panel h-fit p-2"><button v-for="item in tabs" :key="item.id" type="button" :class="['flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold transition',tab===item.id?'bg-violet-600 text-white shadow-lg shadow-violet-100':'text-slate-600 hover:bg-slate-50']" @click="tab=item.id"><UiIcon :name="item.icon" :size="18"/>{{item.label}}</button></aside>
  <div><p v-if="saved" class="mb-4 form-success">Configuración guardada.</p><p v-if="error" class="mb-4 form-error">{{error}}</p><div v-if="loading" class="panel">Cargando configuración…</div>
   <form v-else class="panel form-stack" @submit.prevent="save">
    <template v-if="tab==='general'"><div><h2 class="text-xl font-bold">Información general</h2><p class="text-sm text-slate-500">Nombre, descripción y región principal del sitio.</p></div><label>Nombre del sitio<input v-model="values['site.name']" required maxlength="160"></label><label>Frase principal<input v-model="values['site.tagline']" maxlength="160"></label><label>Descripción<textarea v-model="values['site.description']" rows="5" maxlength="2000"></textarea></label><div class="grid gap-4 md:grid-cols-2"><label>Idioma<select v-model="values['site.locale']"><option value="es-HN">Español · Honduras</option><option value="es-419">Español · Latinoamérica</option><option value="en-US">English</option></select></label><label>Zona horaria<select v-model="values['site.timezone']"><option value="America/Tegucigalpa">America/Tegucigalpa</option><option value="America/Guatemala">America/Guatemala</option><option value="America/Panama">America/Panama</option><option value="UTC">UTC</option></select></label></div></template>
    <template v-else-if="tab==='branding'"><div><h2 class="text-xl font-bold">Identidad visual</h2><p class="text-sm text-slate-500">Recursos globales independientes del tema activo.</p></div><label>URL del logotipo<input v-model="values['branding.logoUrl']" type="url" placeholder="/api/public/media/... o https://..."></label><label>URL del favicon<input v-model="values['branding.faviconUrl']" type="url"></label><label>Color de acento<div class="flex gap-3"><input v-model="values['branding.accentColor']" type="color" class="h-12 w-20"><input v-model="values['branding.accentColor']" pattern="#[0-9a-fA-F]{6}"></div></label></template>
    <template v-else-if="tab==='reading'"><div><h2 class="text-xl font-bold">Lectura y portada</h2><p class="text-sm text-slate-500">Configure qué página funciona como inicio y cómo se presenta el contenido.</p></div><label>Página de inicio<select v-model="values['reading.homePageSlug']" required><option v-for="page in pages" :key="page.id" :value="page.slug">{{page.title}} · /{{page.slug}}</option></select><small>El tema crea páginas locales que puede editar desde la sección Páginas.</small></label><div class="grid gap-4 md:grid-cols-2"><label>Publicaciones por página<input v-model="values['reading.postsPerPage']" type="number" min="1" max="100"></label><label>Formato de fecha<select v-model="values['reading.dateFormat']"><option value="dd/MM/yyyy">31/12/2026</option><option value="MM/dd/yyyy">12/31/2026</option><option value="yyyy-MM-dd">2026-12-31</option></select></label></div><label class="switch-row"><input v-model="values['reading.showAdminBar']" true-value="true" false-value="false" type="checkbox"><span><strong>Barra administrativa en el sitio público</strong><small>Se muestra únicamente a usuarios con sesión iniciada.</small></span></label><label class="switch-row"><input v-model="values['comments.enabled']" true-value="true" false-value="false" type="checkbox"><span><strong>Comentarios</strong><small>Preparar el sitio para plugins de conversación.</small></span></label></template>
    <template v-else-if="tab==='seo'"><div><h2 class="text-xl font-bold">SEO y motores de búsqueda</h2><p class="text-sm text-slate-500">Valores predeterminados que pueden sobrescribirse por página.</p></div><label>Plantilla de título<input v-model="values['seo.titleTemplate']" maxlength="160"><small>Use %s donde debe aparecer el título de la página.</small></label><label>Descripción predeterminada<textarea v-model="values['seo.defaultDescription']" rows="5" maxlength="2000"></textarea></label><label class="switch-row"><input v-model="values['seo.robotsIndex']" true-value="true" false-value="false" type="checkbox"><span><strong>Permitir indexación</strong><small>Desactívelo durante desarrollo o mantenimiento.</small></span></label></template>
    <template v-else-if="tab==='contact'"><div><h2 class="text-xl font-bold">Contacto y redes</h2><p class="text-sm text-slate-500">Información que los temas y plugins pueden reutilizar.</p></div><div class="grid gap-4 md:grid-cols-2"><label>Correo<input v-model="values['contact.email']" type="email"></label><label>Teléfono<input v-model="values['contact.phone']"></label><label>Ciudad<input v-model="values['contact.city']"></label><label>País<input v-model="values['contact.country']"></label></div><label>Dirección<input v-model="values['contact.address']"></label><label>Horario<textarea v-model="values['contact.schedule']" rows="3"></textarea></label><div class="grid gap-4 md:grid-cols-2"><label>Facebook<input v-model="values['contact.facebook']" type="url"></label><label>Instagram<input v-model="values['contact.instagram']" type="url"></label><label>LinkedIn<input v-model="values['contact.linkedin']" type="url"></label><label>YouTube<input v-model="values['contact.youtube']" type="url"></label></div></template>
    <template v-else><div><h2 class="text-xl font-bold">Rendimiento y mantenimiento</h2><p class="text-sm text-slate-500">Parámetros operativos para despliegues productivos.</p></div><div class="grid gap-4 md:grid-cols-2"><label>Caché pública (segundos)<input v-model="values['performance.publicCacheSeconds']" type="number" min="0" max="86400"></label><label>Límite de archivos (MB)<input v-model="values['media.maxUploadMb']" type="number" min="1" max="500"></label></div><label class="switch-row"><input v-model="values['maintenance.enabled']" true-value="true" false-value="false" type="checkbox"><span><strong>Modo mantenimiento</strong><small>Los administradores conservan acceso al panel.</small></span></label></template>
    <button class="button w-fit" :disabled="saving">{{saving?'Guardando…':'Guardar cambios'}}</button>
   </form>
  </div>
 </div>
</template>
