package com.nattechnologies.trastcms.plugins.saas;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nattechnologies.trastcms.plugin.api.PluginEvent;
import com.nattechnologies.trastcms.service.*;
import com.nattechnologies.trastcms.plugins.pay.OrderAccessService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.time.*;
import java.util.*;

@Service
public class SaasService {
    private final SaasProductRepository products; private final SaasPlanRepository plans;
    private final SaasSubscriptionRepository subscriptions; private final SaasLicenseRepository licenses;
    private final SaasActivationRepository activations; private final SaasUsageEventRepository usage;
    private final SaasReleaseRepository releases; private final ObjectMapper mapper;
    private final PluginSecretCipher cipher; private final PluginEventDispatcher events;
    private final SaasPluginGuard guard; private final OrderAccessService orderAccess;
    private final SecureRandom random=new SecureRandom();
    public SaasService(SaasProductRepository products,SaasPlanRepository plans,SaasSubscriptionRepository subscriptions,
                       SaasLicenseRepository licenses,SaasActivationRepository activations,SaasUsageEventRepository usage,
                       SaasReleaseRepository releases,ObjectMapper mapper,PluginSecretCipher cipher,
                       PluginEventDispatcher events,SaasPluginGuard guard,OrderAccessService orderAccess){this.products=products;this.plans=plans;this.subscriptions=subscriptions;this.licenses=licenses;this.activations=activations;this.usage=usage;this.releases=releases;this.mapper=mapper;this.cipher=cipher;this.events=events;this.guard=guard;this.orderAccess=orderAccess;}

    @Transactional public void initializeDefaults(){if(products.count()==0){SaasProduct p=new SaasProduct();p.productKey="trast-cloud";p.name="Trast Cloud";p.description="Plataforma SaaS de ejemplo para demostrar suscripciones, licencias y activaciones.";p.active=true;p=products.save(p);createPlan(p,"starter","Starter","Para profesionales y proyectos pequeños",new BigDecimal("19.00"),1,14,2,Map.of("users.max",3,"projects.max",5,"api.enabled",false,"storage.gb",10),false);createPlan(p,"pro","Pro","Para equipos que necesitan automatización y API",new BigDecimal("49.00"),1,14,10,Map.of("users.max",20,"projects.max",100,"api.enabled",true,"reports.advanced",true,"storage.gb",100),true);createPlan(p,"business","Business","Para organizaciones con soporte y marca blanca",new BigDecimal("129.00"),1,30,100,Map.of("users.max",100,"projects.max",1000,"api.enabled",true,"reports.advanced",true,"white_label.enabled",true,"support.priority",true,"storage.gb",500),false);}}
    private void createPlan(SaasProduct p,String key,String name,String desc,BigDecimal price,int interval,int trial,int max,Map<String,Object> ent,boolean featured){SaasPlan plan=new SaasPlan();plan.product=p;plan.planKey=key;plan.name=name;plan.description=desc;plan.price=price;plan.currency="USD";plan.billingInterval="MONTH";plan.intervalCount=interval;plan.trialDays=trial;plan.maxActivations=max;plan.entitlementsJson=write(ent);plan.active=true;plan.featured=featured;plans.save(plan);}

    @Transactional(readOnly=true) public List<SaasDtos.ProductResponse> products(){guard.requireEnabled();return products.findAll().stream().map(this::product).toList();}
    @Transactional public SaasDtos.ProductResponse saveProduct(String id,SaasDtos.ProductRequest r){guard.requireEnabled();SaasProduct p=id==null?new SaasProduct():requireProduct(id);products.findByProductKey(r.productKey()).filter(x->!Objects.equals(x.id,id)).ifPresent(x->{throw new BadRequestException("La clave del producto ya existe");});p.productKey=r.productKey().trim().toLowerCase(Locale.ROOT);p.name=r.name().trim();p.description=blank(r.description());p.logoUrl=blank(r.logoUrl());p.active=r.active();return product(products.save(p));}
    @Transactional(readOnly=true) public List<SaasDtos.PlanResponse> plans(){guard.requireEnabled();return plans.findAll().stream().map(this::plan).toList();}
    @Transactional(readOnly=true) public List<SaasDtos.PlanResponse> publicPlans(String productKey){guard.requireEnabled();SaasProduct p=products.findByProductKey(productKey).filter(x->x.active).orElseThrow(()->new NotFoundException("Producto SaaS no encontrado"));return plans.findByProductIdAndActiveTrueOrderByPriceAsc(p.id).stream().map(this::plan).toList();}
    @Transactional public SaasDtos.PlanResponse savePlan(String id,SaasDtos.PlanRequest r){guard.requireEnabled();SaasPlan p=id==null?new SaasPlan():requirePlan(id);SaasProduct product=requireProduct(r.productId());plans.findByProductIdAndPlanKey(product.id,r.planKey()).filter(x->!Objects.equals(x.id,id)).ifPresent(x->{throw new BadRequestException("La clave del plan ya existe");});p.product=product;p.planKey=r.planKey().trim().toLowerCase(Locale.ROOT);p.name=r.name().trim();p.description=blank(r.description());p.price=money(r.price());p.currency=r.currency()==null?"USD":r.currency();p.billingInterval=r.billingInterval().toUpperCase(Locale.ROOT);if(!Set.of("DAY","WEEK","MONTH","YEAR","ONE_TIME").contains(p.billingInterval))throw new BadRequestException("Intervalo inválido");p.intervalCount=r.intervalCount();p.trialDays=r.trialDays();p.maxActivations=r.maxActivations();p.entitlementsJson=write(r.entitlements());p.active=r.active();p.featured=r.featured();return plan(plans.save(p));}
    @Transactional public SaasDtos.LicenseResponse issue(SaasDtos.IssueLicenseRequest r){guard.requireEnabled();SaasPlan plan=requirePlan(r.planId());Issued issued=issueLicense(plan,r.customerEmail(),null,r.orderId(),r.expiresAt(),r.maxActivations());return license(issued.license,issued.rawKey);}
    @Transactional public void fulfillPlan(String planId,String customerId,String email,String orderId,int quantity){SaasPlan plan=requirePlan(planId);for(int i=0;i<quantity;i++){SaasSubscription subscription=new SaasSubscription();subscription.plan=plan;subscription.customerId=customerId;subscription.customerEmail=email;subscription.orderId=orderId;subscription.startedAt=Instant.now();subscription.currentPeriodStart=Instant.now();subscription.trialEndsAt=plan.trialDays>0?Instant.now().plus(Duration.ofDays(plan.trialDays)):null;subscription.status=plan.trialDays>0?SubscriptionStatus.TRIALING:SubscriptionStatus.ACTIVE;subscription.currentPeriodEnd=periodEnd(Instant.now(),plan.billingInterval,plan.intervalCount);subscription=subscriptions.save(subscription);issueLicense(plan,email,subscription,orderId,subscription.currentPeriodEnd,plan.maxActivations);}}
    private Issued issueLicense(SaasPlan plan,String email,SaasSubscription subscription,String orderId,Instant expiresAt,Integer maxActivations){String raw=key(plan.product.productKey);SaasLicense l=new SaasLicense();l.product=plan.product;l.plan=plan;l.subscription=subscription;l.customerEmail=email.trim().toLowerCase(Locale.ROOT);l.orderId=orderId;l.keyHash=hash(raw);l.keyCipher=cipher.encrypt(raw);l.keyPrefix=raw.substring(0,Math.min(14,raw.length()));l.status=LicenseStatus.ACTIVE;l.maxActivations=maxActivations==null?plan.maxActivations:maxActivations;l.issuedAt=Instant.now();l.expiresAt=expiresAt;l.graceEndsAt=expiresAt==null?null:expiresAt.plus(Duration.ofDays(7));return new Issued(licenses.save(l),raw);}

    @Transactional public SaasDtos.LicenseResult validate(SaasDtos.LicenseRequest r,boolean activate){guard.requireEnabled();SaasLicense l=requireByKey(r.licenseKey(),r.productKey());refresh(l);if(l.status!=LicenseStatus.ACTIVE)return result(false,l,null,"Licencia "+l.status.name());if(l.expiresAt!=null&&Instant.now().isAfter(l.graceEndsAt==null?l.expiresAt:l.graceEndsAt)){l.status=LicenseStatus.EXPIRED;licenses.save(l);return result(false,l,null,"La licencia expiró");}SaasActivation activation=null;if(activate){if(r.fingerprint()==null||r.fingerprint().isBlank())throw new BadRequestException("fingerprint es obligatorio");String fp=hash(r.fingerprint());activation=activations.findByLicenseIdAndFingerprintHash(l.id,fp).orElse(null);if(activation==null){long active=activations.countByLicenseIdAndStatus(l.id,ActivationStatus.ACTIVE);if(active>=l.maxActivations)throw new BadRequestException("Se alcanzó el máximo de activaciones");activation=new SaasActivation();activation.license=l;activation.fingerprintHash=fp;activation.deviceName=blank(r.deviceName());activation.platform=blank(r.platform());activation.applicationVersion=blank(r.applicationVersion());activation.status=ActivationStatus.ACTIVE;activation.activatedAt=Instant.now();}else if(activation.status!=ActivationStatus.ACTIVE){activation.status=ActivationStatus.ACTIVE;activation.deactivatedAt=null;}activation.lastHeartbeatAt=Instant.now();activation=activations.save(activation);events.publish(PluginEvent.of("saas.license.activated",Map.of("licenseId",l.id,"activationId",activation.id)));}l.lastValidatedAt=Instant.now();licenses.save(l);return result(true,l,activation,"Licencia válida");}
    @Transactional public SaasDtos.LicenseResult heartbeat(SaasDtos.LicenseRequest r){return validate(r,true);}
    @Transactional public void deactivate(SaasDtos.DeactivateRequest r){guard.requireEnabled();SaasLicense l=requireByKey(r.licenseKey(),r.productKey());String fp=hash(r.fingerprint());SaasActivation a=activations.findByLicenseIdAndFingerprintHash(l.id,fp).orElseThrow(()->new NotFoundException("Activación no encontrada"));a.status=ActivationStatus.DEACTIVATED;a.deactivatedAt=Instant.now();activations.save(a);events.publish(PluginEvent.of("saas.license.deactivated",Map.of("licenseId",l.id,"activationId",a.id)));}
    @Transactional public Map<String,Object> usage(SaasDtos.UsageRequest r){guard.requireEnabled();SaasLicense l=requireByKey(r.licenseKey(),r.productKey());if(l.subscription==null)throw new BadRequestException("La licencia no está asociada a una suscripción");var existing=usage.findByIdempotencyKey(r.idempotencyKey());if(existing.isPresent())return Map.of("accepted",true,"duplicate",true,"eventId",existing.get().id);SaasUsageEvent e=new SaasUsageEvent();e.subscription=l.subscription;e.meter=r.meter();e.quantity=r.quantity();e.idempotencyKey=r.idempotencyKey();e.occurredAt=r.occurredAt()==null?Instant.now():r.occurredAt();e.metadataJson=write(r.metadata());e=usage.save(e);events.publish(PluginEvent.of("saas.usage.recorded",Map.of("subscriptionId",l.subscription.id,"meter",e.meter,"quantity",e.quantity)));return Map.of("accepted",true,"duplicate",false,"eventId",e.id);}
    @Transactional(readOnly=true) public SaasDtos.ClaimResponse claim(String orderNumber,String token){guard.requireEnabled();OrderAccessService.OrderAccess access=orderAccess.require(orderNumber,token);String orderId=access.id();String email=access.customerEmail();List<SaasDtos.LicenseResponse> ls=licenses.findByOrderId(orderId).stream().map(l->license(l,cipher.decrypt(l.keyCipher))).toList();List<SaasDtos.SubscriptionResponse> ss=subscriptions.findByOrderId(orderId).stream().map(this::subscription).toList();return new SaasDtos.ClaimResponse(orderNumber,email,ls,ss);}
    @Transactional(readOnly=true) public List<SaasDtos.LicenseResponse> licenses(){guard.requireEnabled();return licenses.findAll().stream().sorted(Comparator.comparing((SaasLicense l)->l.createdAt).reversed()).map(l->license(l,null)).toList();}
    @Transactional(readOnly=true) public List<SaasDtos.SubscriptionResponse> subscriptions(){guard.requireEnabled();return subscriptions.findAll().stream().map(this::subscription).toList();}
    @Transactional public SaasDtos.ReleaseResponse saveRelease(String id,SaasDtos.ReleaseRequest r){guard.requireEnabled();SaasRelease release=id==null?new SaasRelease():releases.findById(id).orElseThrow(()->new NotFoundException("Versión no encontrada"));release.product=requireProduct(r.productId());release.version=r.version();release.platform=r.platform().toLowerCase(Locale.ROOT);release.channel=r.channel()==null?"stable":r.channel().toLowerCase(Locale.ROOT);release.downloadUrl=r.downloadUrl();release.checksum=blank(r.checksum());release.minimumPlan=blank(r.minimumPlan());release.active=r.active();release.publishedAt=r.publishedAt()==null?Instant.now():r.publishedAt();return release(releases.save(release));}
    @Transactional(readOnly=true) public SaasDtos.ReleaseResponse latest(String productKey,String platform,String channel,SaasDtos.LicenseRequest r){SaasLicense l=requireByKey(r.licenseKey(),productKey);if(l.status!=LicenseStatus.ACTIVE)throw new BadRequestException("Licencia inactiva");return releases.findFirstByProductIdAndPlatformAndChannelAndActiveTrueOrderByPublishedAtDesc(l.product.id,platform.toLowerCase(Locale.ROOT),channel==null?"stable":channel.toLowerCase(Locale.ROOT)).map(this::release).orElseThrow(()->new NotFoundException("No hay versiones disponibles"));}
    @Transactional(readOnly=true) public SaasDtos.Dashboard dashboard(){guard.requireEnabled();List<SaasLicense> all=licenses.findAll();List<SaasDtos.LicenseResponse> recent=all.stream().sorted(Comparator.comparing((SaasLicense l)->l.createdAt).reversed()).limit(8).map(l->license(l,null)).toList();return new SaasDtos.Dashboard(products.count(),plans.count(),subscriptions.count(),subscriptions.findAll().stream().filter(s->Set.of(SubscriptionStatus.ACTIVE,SubscriptionStatus.TRIALING).contains(s.status)).count(),all.size(),all.stream().filter(l->l.status==LicenseStatus.ACTIVE).count(),activations.count(),usage.count(),recent,plans.findByActiveTrueOrderByPriceAsc().stream().filter(p->p.featured).map(this::plan).toList());}

    Map<String, Object> entitlements(SaasPlan plan) { return read(plan.entitlementsJson); }

    private SaasLicense requireByKey(String raw,String productKey){SaasLicense l=licenses.findByKeyHash(hash(raw)).orElseThrow(()->new NotFoundException("Licencia inválida"));if(!l.product.productKey.equals(productKey))throw new NotFoundException("Licencia inválida");return l;}private SaasProduct requireProduct(String id){return products.findById(id).orElseThrow(()->new NotFoundException("Producto SaaS no encontrado"));}private SaasPlan requirePlan(String id){return plans.findById(id).orElseThrow(()->new NotFoundException("Plan no encontrado"));}
    private void refresh(SaasLicense l){if(l.status==LicenseStatus.ACTIVE&&l.expiresAt!=null&&Instant.now().isAfter(l.graceEndsAt==null?l.expiresAt:l.graceEndsAt))l.status=LicenseStatus.EXPIRED;}
    private SaasDtos.LicenseResult result(boolean valid,SaasLicense l,SaasActivation a,String message){Map<String,Object> ent=read(l.plan.entitlementsJson);String payload=l.id+"|"+l.status+"|"+Objects.toString(l.expiresAt,"")+"|"+ent;return new SaasDtos.LicenseResult(valid,l.status.name(),l.id,a==null?null:a.id,l.expiresAt,l.graceEndsAt,ent,message,hash(payload));}
    private SaasDtos.ProductResponse product(SaasProduct p){return new SaasDtos.ProductResponse(p.id,p.productKey,p.name,p.description,p.logoUrl,p.active,p.createdAt);}private SaasDtos.PlanResponse plan(SaasPlan p){return new SaasDtos.PlanResponse(p.id,p.product.id,p.product.productKey,p.planKey,p.name,p.description,p.price,p.currency,p.billingInterval,p.intervalCount,p.trialDays,p.maxActivations,read(p.entitlementsJson),p.active,p.featured,p.createdAt,p.updatedAt);}private SaasDtos.SubscriptionResponse subscription(SaasSubscription s){return new SaasDtos.SubscriptionResponse(s.id,s.plan.product.productKey,s.plan.planKey,s.plan.name,s.customerEmail,s.status.name(),s.trialEndsAt,s.currentPeriodStart,s.currentPeriodEnd,s.cancelAtPeriodEnd,s.orderId);}private SaasDtos.LicenseResponse license(SaasLicense l,String raw){long count=activations.countByLicenseIdAndStatus(l.id,ActivationStatus.ACTIVE);return new SaasDtos.LicenseResponse(l.id,l.product.productKey,l.plan.planKey,l.customerEmail,l.keyPrefix+"…",raw,l.status.name(),l.maxActivations,count,l.issuedAt,l.expiresAt,l.graceEndsAt,l.lastValidatedAt,l.orderId);}private SaasDtos.ReleaseResponse release(SaasRelease r){return new SaasDtos.ReleaseResponse(r.id,r.product.productKey,r.version,r.platform,r.channel,r.downloadUrl,r.checksum,r.minimumPlan,r.active,r.publishedAt);}
    private Instant periodEnd(Instant start,String interval,int count){return switch(interval){case"DAY"->start.plus(Duration.ofDays(count));case"WEEK"->start.plus(Duration.ofDays(7L*count));case"YEAR"->start.atZone(ZoneOffset.UTC).plusYears(count).toInstant();case"ONE_TIME"->null;default->start.atZone(ZoneOffset.UTC).plusMonths(count).toInstant();};}private String key(String product){byte[] bytes=new byte[18];random.nextBytes(bytes);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes).toUpperCase(Locale.ROOT);return("TRAST-"+product.toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]","")+"-"+token).replaceAll("(.{8})(?=.)","$1-");}private String hash(String v){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private String write(Object v){try{return mapper.writeValueAsString(v==null?Map.of():v);}catch(Exception e){throw new BadRequestException("Datos inválidos");}}private Map<String,Object> read(String v){try{return v==null?Map.of():mapper.readValue(v,new TypeReference<>(){});}catch(Exception e){return Map.of();}}private String blank(String v){return v==null||v.isBlank()?null:v.trim();}private BigDecimal money(BigDecimal v){return(v==null?BigDecimal.ZERO:v).setScale(2,RoundingMode.HALF_UP);}private record Issued(SaasLicense license,String rawKey){}
}
