package com.nattechnologies.trastcms.plugins.pay;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nattechnologies.trastcms.plugin.api.PaymentGateway;
import com.nattechnologies.trastcms.plugin.api.PluginEvent;
import com.nattechnologies.trastcms.plugin.api.SellableProvider;
import com.nattechnologies.trastcms.service.*;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.*;

@Service
public class PayService {
    private final CommerceCartRepository carts; private final CommerceCustomerRepository customers;
    private final CommerceOrderRepository orders; private final CommercePaymentRepository payments;
    private final CommerceCouponRepository coupons; private final CommerceSettingsRepository configuration; private final CommerceRegistry registry;
    private final ObjectMapper mapper; private final PluginEventDispatcher events; private final PayPluginGuard guard;
    private final SecureRandom random=new SecureRandom();
    public PayService(CommerceCartRepository carts,CommerceCustomerRepository customers,CommerceOrderRepository orders,
                      CommercePaymentRepository payments,CommerceCouponRepository coupons,CommerceSettingsRepository configuration,CommerceRegistry registry,
                      ObjectMapper mapper,PluginEventDispatcher events,PayPluginGuard guard){this.carts=carts;this.customers=customers;this.orders=orders;this.payments=payments;this.coupons=coupons;this.configuration=configuration;this.registry=registry;this.mapper=mapper;this.events=events;this.guard=guard;}

    @Transactional public void initializeDefaults(){if(configuration.findById(CommerceSettings.DEFAULT_ID).isEmpty())configuration.save(new CommerceSettings());}
    @Transactional public PayDtos.CartResponse createCart(String currency){guard.requireEnabled();CommerceSettings settings=currentSettings();CommerceCart c=new CommerceCart();c.currency=normalizeCurrency(currency==null||currency.isBlank()?settings.defaultCurrency:currency);c.expiresAt=Instant.now().plusSeconds(86400L*settings.cartExpirationDays);return cart(carts.save(c),null);}
    @Transactional(readOnly=true) public PayDtos.CartResponse getCart(String token,String coupon){guard.requireEnabled();return cart(requireCart(token),coupon);}
    @Transactional public PayDtos.CartResponse add(String token,PayDtos.AddItemRequest request,String coupon){guard.requireEnabled();CommerceCart cart=requireCart(token);ensureActive(cart);var item=registry.requireItem(request.providerKey(),request.reference());if(!item.available())throw new BadRequestException("El producto no está disponible");if(!cart.currency.equalsIgnoreCase(item.currency()))throw new BadRequestException("El carrito no puede mezclar monedas");CommerceCartItem line=cart.items.stream().filter(existing->existing.providerKey.equals(request.providerKey())&&existing.itemReference.equals(request.reference())&&Objects.equals(existing.metadataJson,write(request.metadata()))).findFirst().orElseGet(()->{CommerceCartItem created=new CommerceCartItem();created.cart=cart;created.providerKey=item.providerKey();created.itemReference=item.reference();created.itemType=item.type();created.name=item.name();created.unitPrice=money(item.unitPrice());created.currency=item.currency();created.metadataJson=write(merge(item.metadata(),request.metadata()));created.quantity=0;cart.items.add(created);return created;});line.quantity=Math.min(999,line.quantity+request.quantity());carts.save(cart);events.publish(PluginEvent.of("commerce.cart.updated",Map.of("cartToken",cart.cartToken,"items",cart.items.size())));return cart(cart,coupon);}
    @Transactional public PayDtos.CartResponse update(String token,String itemId,PayDtos.UpdateItemRequest request,String coupon){guard.requireEnabled();CommerceCart cart=requireCart(token);CommerceCartItem line=cart.items.stream().filter(i->i.id.equals(itemId)).findFirst().orElseThrow(()->new NotFoundException("Línea no encontrada"));if(request.quantity()==0)cart.items.remove(line);else line.quantity=request.quantity();carts.save(cart);return cart(cart,coupon);}
    @Transactional public PayDtos.CartResponse clear(String token){CommerceCart cart=requireCart(token);cart.items.clear();return cart(carts.save(cart),null);}

    @Transactional public PayDtos.CheckoutResponse checkout(String token,PayDtos.CheckoutRequest request){guard.requireEnabled();CommerceCart cart=requireCart(token);ensureActive(cart);if(cart.items.isEmpty())throw new BadRequestException("El carrito está vacío");if(request.idempotencyKey()!=null&&!request.idempotencyKey().isBlank()){var existing=payments.findByIdempotencyKey(request.idempotencyKey());if(existing.isPresent()){CommercePayment p=existing.get();return new PayDtos.CheckoutResponse(p.order.id,p.order.orderNumber,p.order.publicToken,p.order.status.name(),p.id,p.status.name(),p.redirectUrl,"Solicitud procesada previamente");}}
        CommerceCustomer customer=customers.findByEmailIgnoreCase(request.email()).orElseGet(CommerceCustomer::new);customer.email=request.email().trim().toLowerCase(Locale.ROOT);customer.displayName=request.name().trim();customer.phone=blank(request.phone());customer=customers.save(customer);
        Totals totals=totals(cart,request.couponCode());CommerceOrder order=new CommerceOrder();order.orderNumber=orderNumber();order.publicToken=UUID.randomUUID().toString().replace("-","");order.currency=cart.currency;order.customer=customer;order.customerEmail=customer.email;order.customerName=customer.displayName;order.subtotal=totals.subtotal;order.discountTotal=totals.discount;order.taxTotal=totals.tax;order.grandTotal=totals.total;order.couponCode=totals.couponCode;order.billingJson=write(request.billing());order.shippingJson=write(request.shipping());order.notes=blank(request.notes());for(CommerceCartItem ci:cart.items){CommerceOrderItem oi=new CommerceOrderItem();oi.order=order;oi.providerKey=ci.providerKey;oi.itemReference=ci.itemReference;oi.itemType=ci.itemType;oi.name=ci.name;oi.quantity=ci.quantity;oi.unitPrice=ci.unitPrice;oi.lineTotal=money(ci.unitPrice.multiply(BigDecimal.valueOf(ci.quantity)));oi.metadataJson=ci.metadataJson;order.items.add(oi);}order=orders.save(order);
        PaymentGateway gateway=registry.requireGateway(request.gatewayKey());String idem=request.idempotencyKey()==null||request.idempotencyKey().isBlank()?UUID.randomUUID().toString():request.idempotencyKey();PaymentGateway.PaymentResult result=gateway.create(new PaymentGateway.PaymentRequest(order.id,order.orderNumber,order.grandTotal,order.currency,order.customerEmail,request.returnUrl(),request.cancelUrl(),idem,Map.of()));CommercePayment payment=new CommercePayment();payment.order=order;payment.gatewayKey=gateway.key();payment.amount=order.grandTotal;payment.currency=order.currency;payment.externalReference=result.externalReference();payment.redirectUrl=result.redirectUrl();payment.idempotencyKey=idem;payment.metadataJson=write(result.metadata());payment.status=parsePaymentStatus(result.status());payment=payments.save(payment);if(payment.status==PaymentStatus.SUCCEEDED)markPaid(order,payment);else order.status=OrderStatus.PENDING_PAYMENT;orders.save(order);cart.status=CartStatus.CONVERTED;carts.save(cart);events.publish(PluginEvent.of("commerce.order.created",Map.of("orderId",order.id,"orderNumber",order.orderNumber,"total",order.grandTotal)));return new PayDtos.CheckoutResponse(order.id,order.orderNumber,order.publicToken,order.status.name(),payment.id,payment.status.name(),payment.redirectUrl,result.message());}

    @Transactional public PayDtos.OrderResponse markPayment(String paymentId,String status){guard.requireEnabled();CommercePayment payment=payments.findById(paymentId).orElseThrow(()->new NotFoundException("Pago no encontrado"));payment.status=parsePaymentStatus(status);if(payment.status==PaymentStatus.SUCCEEDED)markPaid(payment.order,payment);else if(payment.status==PaymentStatus.FAILED){payment.order.status=OrderStatus.FAILED;orders.save(payment.order);}payments.save(payment);return order(payment.order);}
    @Transactional public PayDtos.OrderResponse updateOrderStatus(String id,String status){guard.requireEnabled();CommerceOrder order=orders.findById(id).orElseThrow(()->new NotFoundException("Orden no encontrada"));try{order.status=OrderStatus.valueOf(status);}catch(Exception e){throw new BadRequestException("Estado inválido");}return order(orders.save(order));}
    @Transactional(readOnly=true) public PayDtos.PageResponse<PayDtos.OrderResponse> orders(int page,int size){guard.requireEnabled();Page<CommerceOrder> result=orders.findAllByOrderByCreatedAtDesc(PageRequest.of(Math.max(0,page),Math.min(Math.max(size,1),100)));return new PayDtos.PageResponse<>(result.map(this::order).getContent(),result.getNumber(),result.getSize(),result.getTotalElements(),result.getTotalPages());}
    @Transactional(readOnly=true) public PayDtos.OrderResponse order(String id){guard.requireEnabled();return order(orders.findById(id).orElseThrow(()->new NotFoundException("Orden no encontrada")));}
    @Transactional(readOnly=true) public PayDtos.Dashboard dashboard(){guard.requireEnabled();List<CommerceOrder> all=orders.findAll();BigDecimal revenue=all.stream().filter(o->Set.of(OrderStatus.PAID,OrderStatus.COMPLETED).contains(o.status)).map(o->o.grandTotal).reduce(BigDecimal.ZERO,BigDecimal::add);List<PayDtos.OrderResponse> recent=orders.findAllByOrderByCreatedAtDesc(PageRequest.of(0,8)).map(this::order).getContent();return new PayDtos.Dashboard(all.size(),all.stream().filter(o->o.status==OrderStatus.PAID||o.status==OrderStatus.COMPLETED).count(),all.stream().filter(o->o.status==OrderStatus.PENDING_PAYMENT).count(),money(revenue),payments.count(),coupons.count(),recent,registry.gateways());}
    @Transactional(readOnly=true) public List<PayDtos.CouponResponse> coupons(){guard.requireEnabled();return coupons.findAll().stream().map(this::coupon).toList();}
    @Transactional public PayDtos.CouponResponse saveCoupon(String id,PayDtos.CouponRequest r){guard.requireEnabled();CommerceCoupon c=id==null?new CommerceCoupon():coupons.findById(id).orElseThrow(()->new NotFoundException("Cupón no encontrado"));coupons.findByCodeIgnoreCase(r.code()).filter(x->!Objects.equals(x.id,id)).ifPresent(x->{throw new BadRequestException("El código ya existe");});c.code=r.code().trim().toUpperCase(Locale.ROOT);c.discountType=r.discountType().trim().toUpperCase(Locale.ROOT);if(!Set.of("PERCENT","FIXED").contains(c.discountType))throw new BadRequestException("Tipo de descuento inválido");c.discountValue=r.discountValue();c.minimumAmount=r.minimumAmount();c.maximumUses=r.maximumUses();c.startsAt=r.startsAt();c.endsAt=r.endsAt();c.active=r.active();return coupon(coupons.save(c));}
    @Transactional public void deleteCoupon(String id){guard.requireEnabled();coupons.deleteById(id);}
    @Transactional(readOnly=true) public PayDtos.SettingsResponse settings(){guard.requireEnabled();return settings(currentSettings());}
    @Transactional public PayDtos.SettingsResponse saveSettings(PayDtos.SettingsRequest request){guard.requireEnabled();CommerceSettings value=currentSettings();value.defaultCurrency=normalizeCurrency(request.defaultCurrency());value.taxRate=money(request.taxRate()==null?BigDecimal.ZERO:request.taxRate());if(value.taxRate.compareTo(new BigDecimal("100"))>0)throw new BadRequestException("La tasa de impuesto no puede superar 100%");value.cartExpirationDays=request.cartExpirationDays();value.guestCheckout=request.guestCheckout();value.collectShipping=request.collectShipping();value.companyName=blank(request.companyName());value.supportEmail=blank(request.supportEmail());value.termsUrl=blank(request.termsUrl());value.bankInstructions=blank(request.bankInstructions());return settings(configuration.save(value));}
    public List<Map<String,Object>> gateways(){guard.requireEnabled();return registry.gateways();}

    private void markPaid(CommerceOrder order,CommercePayment payment){if(order.paidAt==null){order.status=OrderStatus.PAID;order.paidAt=Instant.now();orders.save(order);for(CommerceOrderItem item:order.items){if(item.fulfilledAt==null){registry.requireProvider(item.providerKey).fulfill(new SellableProvider.FulfillmentRequest(order.id,order.orderNumber,order.customer.id,order.customerEmail,item.itemReference,item.quantity,read(item.metadataJson)));item.fulfilledAt=Instant.now();}}orders.save(order);if(order.couponCode!=null)coupons.findByCodeIgnoreCase(order.couponCode).ifPresent(c->{c.usedCount++;coupons.save(c);});events.publish(PluginEvent.of("commerce.payment.succeeded",Map.of("orderId",order.id,"paymentId",payment.id,"amount",payment.amount)));}}
    private CommerceCart requireCart(String token){return carts.findByCartToken(token).orElseThrow(()->new NotFoundException("Carrito no encontrado"));}
    private void ensureActive(CommerceCart cart){if(cart.status!=CartStatus.ACTIVE||cart.expiresAt.isBefore(Instant.now()))throw new BadRequestException("El carrito ya no está activo");}
    private PayDtos.CartResponse cart(CommerceCart c,String code){Totals t=totals(c,code);List<PayDtos.CartItemResponse> lines=c.items.stream().map(i->{var item=registry.requireItem(i.providerKey,i.itemReference);return new PayDtos.CartItemResponse(i.id,i.providerKey,i.itemReference,i.itemType,i.name,i.quantity,i.unitPrice,money(i.unitPrice.multiply(BigDecimal.valueOf(i.quantity))),i.currency,item.imageUrl(),read(i.metadataJson));}).toList();return new PayDtos.CartResponse(c.cartToken,c.status.name(),c.currency,lines,t.subtotal,t.discount,t.tax,t.total,c.expiresAt);}
    private Totals totals(CommerceCart c,String code){BigDecimal subtotal=c.items.stream().map(i->i.unitPrice.multiply(BigDecimal.valueOf(i.quantity))).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal discount=BigDecimal.ZERO;String normalized=null;if(code!=null&&!code.isBlank()){CommerceCoupon coupon=coupons.findByCodeIgnoreCase(code).orElseThrow(()->new BadRequestException("Cupón inválido"));Instant now=Instant.now();if(!coupon.active||(coupon.startsAt!=null&&coupon.startsAt.isAfter(now))||(coupon.endsAt!=null&&coupon.endsAt.isBefore(now))||(coupon.maximumUses!=null&&coupon.usedCount>=coupon.maximumUses)||(coupon.minimumAmount!=null&&subtotal.compareTo(coupon.minimumAmount)<0))throw new BadRequestException("El cupón no está disponible");discount=coupon.discountType.equals("PERCENT")?subtotal.multiply(coupon.discountValue).divide(BigDecimal.valueOf(100),4,RoundingMode.HALF_UP):coupon.discountValue;discount=discount.min(subtotal);normalized=coupon.code;}BigDecimal taxable=subtotal.subtract(discount);BigDecimal tax=taxable.multiply(currentSettings().taxRate).divide(BigDecimal.valueOf(100),4,RoundingMode.HALF_UP);return new Totals(money(subtotal),money(discount),money(tax),money(taxable.add(tax)),normalized);}
    private PayDtos.OrderResponse order(CommerceOrder o){return new PayDtos.OrderResponse(o.id,o.orderNumber,o.status.name(),o.currency,o.customerEmail,o.customerName,o.subtotal,o.discountTotal,o.taxTotal,o.grandTotal,o.couponCode,o.items.stream().map(i->new PayDtos.OrderLine(i.id,i.providerKey,i.itemReference,i.itemType,i.name,i.quantity,i.unitPrice,i.lineTotal,i.fulfilledAt!=null)).toList(),o.paidAt,o.createdAt,o.updatedAt);}
    private PayDtos.CouponResponse coupon(CommerceCoupon c){return new PayDtos.CouponResponse(c.id,c.code,c.discountType,c.discountValue,c.minimumAmount,c.maximumUses,c.usedCount,c.startsAt,c.endsAt,c.active);}
    private CommerceSettings currentSettings(){return configuration.findById(CommerceSettings.DEFAULT_ID).orElseGet(CommerceSettings::new);}
    private PayDtos.SettingsResponse settings(CommerceSettings s){return new PayDtos.SettingsResponse(s.defaultCurrency,s.taxRate,s.cartExpirationDays,s.guestCheckout,s.collectShipping,s.companyName,s.supportEmail,s.termsUrl,s.bankInstructions,s.updatedAt);}
    private PaymentStatus parsePaymentStatus(String v){try{return PaymentStatus.valueOf(v.toUpperCase(Locale.ROOT));}catch(Exception e){return PaymentStatus.PENDING;}}
    private String orderNumber(){return "TR-"+java.time.format.DateTimeFormatter.ofPattern("yyyyMMdd").withZone(java.time.ZoneOffset.UTC).format(Instant.now())+"-"+(100000+random.nextInt(900000));}
    private String normalizeCurrency(String c){String value=c==null||c.isBlank()?"USD":c.trim().toUpperCase(Locale.ROOT);if(!value.matches("[A-Z]{3}"))throw new BadRequestException("Moneda inválida");return value;}
    private BigDecimal money(BigDecimal v){return v.setScale(2,RoundingMode.HALF_UP);}
    private String write(Object value){try{return mapper.writeValueAsString(value==null?Map.of():value);}catch(Exception e){throw new BadRequestException("Datos inválidos");}}
    private Map<String,Object> read(String value){try{return value==null||value.isBlank()?Map.of():mapper.readValue(value,new TypeReference<>(){});}catch(Exception e){return Map.of();}}
    private Map<String,Object> merge(Map<String,Object>a,Map<String,Object>b){Map<String,Object> result=new LinkedHashMap<>();if(a!=null)result.putAll(a);if(b!=null)result.putAll(b);return result;}
    private String blank(String v){return v==null||v.isBlank()?null:v.trim();}
    private record Totals(BigDecimal subtotal,BigDecimal discount,BigDecimal tax,BigDecimal total,String couponCode){}
}
