CREATE TABLE commerce_customer (id VARCHAR(36) PRIMARY KEY,email VARCHAR(190) NOT NULL,display_name VARCHAR(190),phone VARCHAR(60),metadata_json TEXT,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX ux_commerce_customer_email ON commerce_customer(email);
CREATE TABLE commerce_cart (id VARCHAR(36) PRIMARY KEY,cart_token VARCHAR(80) NOT NULL UNIQUE,status VARCHAR(30) NOT NULL,currency VARCHAR(3) NOT NULL,customer_id VARCHAR(36),expires_at TIMESTAMP,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,CONSTRAINT fk_cart_customer FOREIGN KEY(customer_id) REFERENCES commerce_customer(id));
CREATE TABLE commerce_cart_item (id VARCHAR(36) PRIMARY KEY,cart_id VARCHAR(36) NOT NULL,provider_key VARCHAR(80) NOT NULL,item_reference VARCHAR(120) NOT NULL,item_type VARCHAR(50) NOT NULL,name VARCHAR(240) NOT NULL,quantity INT NOT NULL,unit_price DECIMAL(19,4) NOT NULL,currency VARCHAR(3) NOT NULL,metadata_json TEXT,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,CONSTRAINT fk_cart_item_cart FOREIGN KEY(cart_id) REFERENCES commerce_cart(id) ON DELETE CASCADE);
CREATE TABLE commerce_order (id VARCHAR(36) PRIMARY KEY,order_number VARCHAR(40) NOT NULL UNIQUE,public_token VARCHAR(80) NOT NULL UNIQUE,status VARCHAR(40) NOT NULL,currency VARCHAR(3) NOT NULL,customer_id VARCHAR(36),customer_email VARCHAR(190) NOT NULL,customer_name VARCHAR(190),subtotal DECIMAL(19,4) NOT NULL,discount_total DECIMAL(19,4) NOT NULL,tax_total DECIMAL(19,4) NOT NULL,grand_total DECIMAL(19,4) NOT NULL,coupon_code VARCHAR(80),billing_json TEXT,shipping_json TEXT,notes TEXT,paid_at TIMESTAMP,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,CONSTRAINT fk_order_customer FOREIGN KEY(customer_id) REFERENCES commerce_customer(id));
CREATE TABLE commerce_order_item (id VARCHAR(36) PRIMARY KEY,order_id VARCHAR(36) NOT NULL,provider_key VARCHAR(80) NOT NULL,item_reference VARCHAR(120) NOT NULL,item_type VARCHAR(50) NOT NULL,name VARCHAR(240) NOT NULL,quantity INT NOT NULL,unit_price DECIMAL(19,4) NOT NULL,line_total DECIMAL(19,4) NOT NULL,metadata_json TEXT,fulfilled_at TIMESTAMP,CONSTRAINT fk_order_item_order FOREIGN KEY(order_id) REFERENCES commerce_order(id) ON DELETE CASCADE);
CREATE TABLE commerce_payment (id VARCHAR(36) PRIMARY KEY,order_id VARCHAR(36) NOT NULL,gateway_key VARCHAR(80) NOT NULL,status VARCHAR(40) NOT NULL,amount DECIMAL(19,4) NOT NULL,currency VARCHAR(3) NOT NULL,external_reference VARCHAR(190),redirect_url VARCHAR(1000),idempotency_key VARCHAR(120) UNIQUE,metadata_json TEXT,failure_message TEXT,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,CONSTRAINT fk_payment_order FOREIGN KEY(order_id) REFERENCES commerce_order(id));
CREATE TABLE commerce_coupon (id VARCHAR(36) PRIMARY KEY,code VARCHAR(80) NOT NULL UNIQUE,discount_type VARCHAR(20) NOT NULL,discount_value DECIMAL(19,4) NOT NULL,minimum_amount DECIMAL(19,4),maximum_uses INT,used_count INT NOT NULL,starts_at TIMESTAMP,ends_at TIMESTAMP,active BOOLEAN NOT NULL);
CREATE INDEX ix_order_status ON commerce_order(status); CREATE INDEX ix_order_email ON commerce_order(customer_email); CREATE INDEX ix_payment_order ON commerce_payment(order_id);

CREATE TABLE commerce_settings (id VARCHAR(40) PRIMARY KEY,default_currency VARCHAR(3) NOT NULL,tax_rate DECIMAL(8,4) NOT NULL,cart_expiration_days INT NOT NULL,guest_checkout BOOLEAN NOT NULL,collect_shipping BOOLEAN NOT NULL,company_name VARCHAR(190),support_email VARCHAR(190),terms_url VARCHAR(1000),bank_instructions VARCHAR(4000),updated_at TIMESTAMP NOT NULL);
